export const contents = {
  "title": "안녕하세요, 프론트엔드 개발자 문승희입니다.",
  "subTitle": "새로운 것을 배우는 것을 좋아하며 어떤게 좋은 코드인가를 함께 고민하는 것을 좋아합니다. \n서비스의 시작과 끝은 UI/UX가 결정한다는 생각으로 이를 중요시하며 개발합니다.\n커뮤니케이션에 능하며 함께 일할때 가장 큰 시너지가 나오는 사람입니다.\n맡은 바 업무는 책임을 다하며 함께 일하고 싶은 사람으로 기억되기 위해 노력합니다.",
  "education_title_1": "프로그래머스 빅데이터 플랫폼 프론트엔드 엔지니어링",
  "education_period_1": "21.07 - 21.12",
  "education_desc_1": "CSS, JavaScript, Vanilla, Vue, React, D3 실습 개인 및 팀 프로젝트 커리큘럼 진행",
  "education_title_2": "위코드 코딩 부트캠프",
  "education_period_2": "20.11 ~ 21.02",
  "education_desc_2": "백엔드 개발자 양성 과정 교육 진행",
  "education_title_3": "케이에스엠 컴포넌트",
  "education_period_3": "18.01 - 20.09 / (주임)",
  "education_desc_3": "반도체/OLED 반도체 장비 부품 기술영업 직무 수행",
  "we_main_title_1": "콜라비팀",
  "we_main_period_1": "2022.06 - 2023.05",
  "we_title_1": "커뮤니티형 메신저 어플리케이션 개발",
  "we_period_1": "2023.01 - 2023.04",
  "we_desc_1": "모바일 어플리케이션의 프론트엔드를 개발했습니다. \n비즈니스 요구에 맞는 다양한 메신저 관련 기능들을 개발하였으며 프로젝트 초기부터 서비스 출시까지 완수하였습니다. ",
  "we_stacks_1": "React, Typescript, React-Native, React-Query, Recoil, Websocket, Styeld-Components, Storybook, I18Next",
  "we_role_1": "[페이지 및 컴포넌트 UI 개발/사용자, 채널 검색 기능 개발/입력창 금칙어, 중복, 생년월일 검증 유틸 함수 개발/i18Next를 이용한 12개국 다국어 지원/소켓 이벤트 수신 및 데이터 갱신 처리]",
  "we_title_2": "커뮤니티형 메신저 어플리케이션 개발",
  "we_period_2": "2022.06 - 2022.12",
  "we_desc_2": "데스크탑 어플리케이션의 프론트엔드를 개발했습니다. \n컴포넌트 및 라우팅 설계, 메신저 어드민 개발 등  비즈니스 요구에 맞는 다양한 메신저 관련 기능들을 개발하였습니다.",
  "we_stacks_2": "React, Typescript, Electron, React-Query, Recoil, Websocket, Styeld-Components, MUI, Storybook, I18Next",
  "we_role_2": "[페이지 및 컴포넌트 UI 개발/대화방, 알람, 사용자 메신저 관련 기능 개발/서비스 랜딩 페이지 개발/메신저 어드민 개발/소켓 이벤트 수신 및 데이터 갱신 처리]"
};
